{ "rows" : 10, 
    "cols" : 10, 
    "grid" : { 
        "d1" : { "desc" : "DT. Stone floor, Wooden table", "note" : "B" }, 
        "h1" : { "tile": false }, 
        "i1" : { "tile": false }, 
        "j1" : { "tile": false}, 
        "c2" : { "note": "S", "desc" : "Stone floor, wooden chair" }, 
        "d2" : { "desc" : "DT. Stone floor, Wooden table", "note" : "B"}, 
        "e2" : { "note": "S", "desc" : "Stone floor, wooden chair" }, 
        "g2" : { "note": "S", "desc" : "Stone floor, wooden chair" }, 
        "h2" : { "tile": false }, 
        "i2" : { "tile": false }, 
        "j2" : { "tile": false }, 
        "c3" : { "note": "S", "desc" : "Stone floor, wooden chair" }, 
        "d3" : { "desc" : "DT. Stone floor, Wooden table", "note" : "B" }, 
        "h3" : { "tile": false }, 
        "j3" : { "tile": false }, 
        "j4" : { "tile": false }, 
        "h5" : { "tile": false }, 
        "i5" : { "tile": false }, 
        "j5" : { "tile": false }, 
        "f6" : { "desc" : "DT. Stone floor, Wooden table", "note" : "B" }, 
        "g6" : { "desc" : "DT. Stone floor, Wooden table", "note" : "B" }, 
        "h6" : { "tile": false }, 
        "i6" : { "tile": false }, 
        "j6" : { "tile": false }, 
        "f7" : { "note": "S", "desc" : "Stone floor, wooden chair" }, 
        "h7" : { "tile": false }, 
        "i7" : { "tile": false }, 
        "j7" : { "tile": false }, 
        "a8" : { "tile": false }, 
        "b8" : { "tile": false }, 
        "c8" : { "tile": false }, 
        "e8" : { "tile": false }, 
        "f8" : { "tile": false }, 
        "g8" : { "tile": false }, 
        "h8" : { "tile": false }, 
        "i8" : { "tile": false }, 
        "j8" : { "tile": false }, 
        "h9" : { "tile": false }, 
        "i9" : { "tile": false }, 
        "j9" : { "tile": false }, 
        "h10" : { "tile": false }, 
        "i10" : { "tile": false }, 
        "j10" : { "tile": false } 
    },
    "element" : {
        "nok" : { "pos" : "f4", "name" : "Nokar", "icon": "classm2x8",   "info" : "Nokar. Deva Avenger. Bloddied. Prone.", "priv_info" : "Liker å gutse" }, 
        "bal" : { "pos" : "i3", "name" : "Baal", "icon" : "monster1_6x2",  "info" : "Baal. Tiefling Wizard lvl1", "priv_info" : "Farlig sjarmerende" }, 
        "tha" : { "pos" : "i4", "name" : "Tharsul", "icon" : "classm10x5", "info" : "Tharsul. Sjeledød Shaman", "priv_info" : "Vil at ting skal dø" }, 
        "bro" : { "pos" : "e6", "name" : "Tharsul - Bror", "icon" : "undead2x7", "info" : "Bror. Tharsul sin spirit" }, 
        "nik" : { "pos" : "h4", "name" : "Nikodamus",   "icon": "classm2x4", "info" : "Nikodamus. Human spydkriger.", "priv_info" : "Glory of battle" }, 
        "pre" : { "pos" : "d8", "icon" : "humans2x1", "name" : "Prest",   "info" : "Prest", "priv_info" : "Muahaha" }, 
        "fa1" : { "pos" : "g4", "icon" : "humans2x5", "text" : "1",  "name" : "Fanatiker 1",  "info" : "Fanatiker. Bloodied", "priv_info" : "asdads"}, 
        "fa2" : { "pos" : "g5", "icon" : "humans2x5", "text" : "2", "name" : "Fanatiker 2",  "info" : "Fanatiker. Bloodied", "priv_info" : "asdads"}, 
        "ku1" : { "pos" : "g3", "icon" : "humans2x4", "text" : "1", "name" : "Kultist 1" }, 
        "ku2" : { "show": false, "pos" : " g3", "name" : "Kultist 2",  "info" : "Fanatiker. Bloodied", "priv_info" : "asdads"}, 
        "ku5" : { "pos" : "e5", "icon" : "humans2x4", "text" : "5", "name": "Kultist 5",   "info" : "Fanatiker. Bloodied", "priv_info" : "asdads"},
    },
		"order" : [ "nok", "bal", "tha", "bro", "nik", "pre", "fa1", "fa2", "ku1", "ku2", "ku5"]
}
